os: linux
language: node_js
node_js:
 - stable
 - lts/*
cache:
    directories:
      - node_modules
branches:
  only:
    - main
jobs:
  include:
    - stage: release
      script:
        - npm run test
      after_success:
        - npm run semantic-release